[[main]]
name = "Início"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "#about"
weight = 2

[[main]]
name = "Envío de Charlas"
url = "#cfp"
weight = 3

[[main]]
name = "Blog"
url = "#blog"
weight = 4

[[main]]
name = "Patrocinadores"
url = "#sponsors"
weight = 5

[[main]]
name = "Código de Conducta"
url = "/codigo-de-conducta/"
weight = 6
